- name: Copy mongodb repo file
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongpdb
  yum:
    name: mongodb-org
    state: installed
#
#- name: Config change of mongodb
#  replace:
#    path: /etc/mongod.conf
#    regexp: '127.0.0.1'
#    replace: '0.0.0.0'

- name: Config change of MongoDB to listen on 0.0.0.0
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^  bindIp'
    line: '  bindIp: 0.0.0.0'

- name: Restart Mongodb
  systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Download from Github
  include_role:
    name: common
    tasks_from: download-github

#- name: Load Scheme
#    shell: mongo < catalogue.js && mongo < users.js
#    args:
#      chdir: /tmp/mongodb-main/

- name: Load Scheme
  shell: mongo < {{ item }}
  args:
    chdir: /tmp/mongodb-main/
  loop:
    - catalogue.js
    - users.js


#  mongodb_shell:
#    file: "/tmp/mongodb-main/users.js"
#    idempotent: yes

#  # mongo < catalogue.js
#  # mongo < users.js
#
#  Symbol < will take the input from a file and give that input to the command.