- name: RoboShop Project Setup
  hosts: all
  become: yes
  tasks:
    - name: Import frontend Role
      import_role:
        name: frontend

    - name: Import Mongodb Role
      import_role:
        - name: mongodb
