- name: OS Pre-reqs
  include_role:
    name: common
    tasks_from: os-prereqs

- name: Setup Yum repos for mysql
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove maridb libs
  yum:
    name: mariadb-libs
    state: absent

- name: install mysql server
  yum:
    name:
    - mysql-community-server
    - MySQL-python
    state: installed

- name: start mysql
  systemd:
    name: mysqld
    state: started
    enabled: yes


- name: Check if mysql PW is set
  mysql_info:
    login_user: "root"
    login_password: "RoboShop@123"
    filter: version
  ignore_erros: yes
  register: out

- name: debug
  debug:
    msg: "{{out}}"



