- name: install NodeJS
  yum:
    name: maven
    state: present

- name: create Roboshop User
  user:
    name: roboshop

- name: Download from Github
  include_role:
    name: common
    tasks_from: download-github

- name: Install maven Deps and compile code
  shell: mvn clean package
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Copy artifact to Project Path
  shell: mv target/shipping-1.0.jar shipping.jar
  args:
    - chdir: /home/roboshop/{{COMPONENT}}

- name: Setup Systemd for {{COMPONENET}}
  include_tasks: "systemd.yml"
