


## mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service
## systemctl daemon-reload
## systemctl start catalogue
## systemctl enable catalogue

- name: setup systemd service
  shell: mv /home/roboshop/{{COMPONENT}}/systemd.service /etc/systemd/system/{{COMPONENT}}.service

- name: Replace End Points in Systemd configuration
  replace:
    path: /etc/systemd/system/{{COMPONENT}}.service
    regexp: "{{item.name}}"
    replace: "{{item.endpoint}}"
  loop:
    - {name: "MONGO_DNSNAME", endpoint: "mongodb-{{ENV}}.vinodmcs21.com"}
    - {name: "REDIS_ENDPOINT", endpoint: "redis-{{ENV}}.vinodmcs21.com"}
    - {name: "MONGO_ENDPOINT", endpoint: "mongodb-{{ENV}}.vinodmcs21.com"}
    - {name: "CATALOGUE_ENDPOINT", endpoint: "catalogue-{{ENV}}.vinodmcs21.com"}
    - {name: "CARTENDPOINT", endpoint: "cart-{{ENV}}.vinodmcs21.com"}
    - {name: "DBHOST", endpoint: "mysql-{{ENV}}.vinodmcs21.com"}
    - {name: "CARTHOST", endpoint: "cart-{{ENV}}.vinodmcs21.com" }
    - {name: "USERHOST", endpoint: "user-{{ENV}}.vinodmcs21.com" }
    - {name: "AMQPHOST", endpoint: "rabbitmq-{{ENV}}.vinodmcs21.com" }



- name: Restart {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon-reload: yes